// Predefined mixer activities

import type { Activity } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: 'champagne-shackles',
    name: 'Champagne & Shackles',
    category: 'icebreaker',
    description: 'Pairs from opposite groups get "shackled" together and must stay within 5 feet for the first hour.',
    instructions: 'Prepare name cards for all participants. Create random pairings (one from each group). Have timer ready (1 hour). Prepare challenge cards or prompts.',
    supplies: 'Name cards, Timer, Challenge prompts',
    minPeople: 8,
    maxPeople: 30,
    energyLevel: 7,
    alcoholRelated: true,
    durationMinutes: 90,
  },
  {
    id: 'speed-friending',
    name: 'Speed Friending',
    category: 'icebreaker',
    description: 'Rotating 5-minute conversations where members from each group get to meet everyone.',
    instructions: 'Arrange chairs in two parallel rows. Divide groups to sit facing each other. Prepare conversation starter cards. Set 5-minute timer for rotations.',
    supplies: 'Chairs, Timer, Conversation prompt cards',
    minPeople: 6,
    maxPeople: 20,
    energyLevel: 4,
    alcoholRelated: false,
    durationMinutes: 60,
  },
  {
    id: 'powerpoint-roulette',
    name: 'PowerPoint Roulette',
    category: 'competition',
    description: "Teams present random PowerPoint slides they've never seen before. Hilarity ensues.",
    instructions: 'Prepare 5-6 random PowerPoint decks (bizarre topics). Create mixed teams of 2-3 people. Set up projection or large screen. Have voting system ready.',
    supplies: 'Laptop, Projector/TV, Random PowerPoint decks, Voting cards',
    minPeople: 10,
    maxPeople: 24,
    energyLevel: 8,
    alcoholRelated: false,
    durationMinutes: 45,
  },
  {
    id: 'most-likely-to',
    name: 'Most Likely To',
    category: 'icebreaker',
    description: "Group voting game where you guess who's most likely to do various things.",
    instructions: 'Arrange seating in a circle or U-shape. Prepare "Most Likely To" prompt list. Explain pointing rules. Keep it lighthearted and fun.',
    supplies: 'Prompt list, Optional: drinks',
    minPeople: 8,
    maxPeople: 25,
    energyLevel: 5,
    alcoholRelated: false,
    durationMinutes: 30,
  },
  {
    id: 'group-charades',
    name: 'Group Charades',
    category: 'competition',
    description: 'Classic charades but with mixed teams competing against each other.',
    instructions: 'Divide into mixed teams. Prepare charades prompts (movies, songs, actions). Designate performance area. Set up timer and scoreboard.',
    supplies: 'Timer, Prompt cards, Scoreboard',
    minPeople: 8,
    maxPeople: 30,
    energyLevel: 7,
    alcoholRelated: false,
    durationMinutes: 45,
  },
  {
    id: 'two-truths-one-lie',
    name: 'Two Truths & a Lie',
    category: 'icebreaker',
    description: 'Go around sharing three statements - others guess which is the lie.',
    instructions: 'Sit in circle with groups mixed. Give everyone 2 minutes to prepare their statements. Establish speaking order. Keep time to 3-4 minutes per person.',
    minPeople: 6,
    maxPeople: 16,
    energyLevel: 3,
    alcoholRelated: false,
    durationMinutes: 40,
  },
  {
    id: 'scavenger-hunt',
    name: 'Campus Scavenger Hunt',
    category: 'competition',
    description: 'Mixed teams race to complete photo challenges around campus or the venue.',
    instructions: 'Create challenge list (10-15 items). Form mixed teams. Set time limit (45-60 minutes). Establish meeting point and end time.',
    supplies: 'Challenge list, Smartphones, Group chat',
    minPeople: 12,
    maxPeople: 40,
    energyLevel: 9,
    alcoholRelated: false,
    durationMinutes: 75,
  },
  {
    id: 'trivia-battle',
    name: 'Trivia Battle',
    category: 'competition',
    description: 'Mixed teams compete in trivia with various categories.',
    instructions: 'Prepare trivia questions (5 categories, 8 questions each). Create mixed teams. Set up answer sheets. Designate scorekeeper.',
    supplies: 'Trivia questions, Answer sheets, Pens, Scoreboard',
    minPeople: 9,
    maxPeople: 30,
    energyLevel: 5,
    alcoholRelated: false,
    durationMinutes: 50,
  },
  {
    id: 'never-have-i-ever',
    name: 'Never Have I Ever',
    category: 'drinking_game',
    description: "Classic game where people share experiences and others indicate if they've done it.",
    instructions: 'Arrange seating in circle. Explain the rules clearly. Set boundaries on appropriateness. Go around circle taking turns.',
    minPeople: 6,
    maxPeople: 20,
    energyLevel: 4,
    alcoholRelated: true,
    durationMinutes: 30,
  },
  {
    id: 'minute-to-win-it',
    name: 'Minute to Win It',
    category: 'competition',
    description: 'Fast-paced physical challenges that must be completed in under 60 seconds.',
    instructions: 'Set up challenge stations. Prepare materials (cups, ping pong balls, cookies, etc.). Designate timer and judge. Create bracket or rotation schedule.',
    supplies: 'Various challenge materials, Timer, Tables',
    minPeople: 8,
    maxPeople: 24,
    energyLevel: 9,
    alcoholRelated: false,
    durationMinutes: 60,
  },
];

export function getRandomActivity(): Activity {
  const randomIndex = Math.floor(Math.random() * ACTIVITIES.length);
  return ACTIVITIES[randomIndex]!;
}

export function getActivityById(id: string): Activity | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}
